### ISSUE TITLE
NTVS v1.2 Beta

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1001]
> _**:runner: in progress and preliminary planning notes for next release.**_

Splitting off our Visual Studio "15" work into a [future release](https://github.com/Microsoft/nodejstools/issues/948), so we can ship for VS 2015 sooner. 

This release will ship for:
* VS 2015 (Dev14)

**Emoji legend**
* :hotsprings: [_**red-hots**_](https://github.com/Microsoft/nodejstools/labels/red-hots) (like the candy!): should happen this week, otherwise may impede future efforts
* :busts_in_silhouette: [**_external dependency_**](https://github.com/Microsoft/nodejstools/labels/external): requires coordination
* :no_entry_sign: **_blocked_**

##### Improved IntelliSense experiences
* [x] #981 ES6 IntelliSense UX improvements a day ago
* [x] #995 Synchronize Node.js <-> TS settings
* [x] #958 Verify no regressions in VS2015 Salsa _**(:busts_in_silhouette: Salsa - billti, jasonra)**_
* [x] Verify latest TypeScript changes (**Update 3 RTM only**) _**(:busts_in_silhouette: Salsa - billti, jasonra)**_
  * [x] #928 Salsa Error after 5 min
  * [x] #817 ES6 IntelliSense Preview does not understand "require"

##### More reliable debugging
* [x] #935 Hang on Remove Breakpoint
* [x] #979 Fixed "ReferenceError: dbg is not defined" error
* [x] #968 Fix hang when sending debug commands after Node program runs to completion

##### Improved Unit Testing experiences
* [x] #941 Support customizing mocha path through mocha.json
* [x] #982 Let JavaScript test frameworks use 0-based line and column numbers

##### Interactive window improvements
* [x] #808 Allow running .npm command sin REPL window from any project type
* [x] #996 Fix Interactive window .npm commands sometimes failing in VS 2015 update 3
* [x] #742 Repl window output perf improvements

##### Other
* [x] #784 Support unc paths for command execution

##### Stability and performance
* [x] #962 Investigate and fix miscellaneous stability issues

## Verification
* [x] #985 Verify quality
* [x] :hotsprings: Address ship-stoppers
  * [x] #998 Slight clipping of text in es5 Intellisense pane
  * [x] #991 Update Typings Acquisition / Intellisense Wiki pages
  * [x] #999 Split usages of aka.ms/NtvsEs6Preview into separate fwlinks
  * [x] #1007 IntelliSense InfoBar typings folder link should open built-in VS browser
  * [x] #1003 Update 2 Gating for installer doesn't work

## Targets (subject to change)
* **6/6**: "Big Rocks" complete
* **6/6-6/9:** Stabilization and [release activities](https://github.com/microsoft/nodejstools/wiki/Release-Activities-Checklist)
* **TBD:** Release

**Comment by jcansdale** [comment]
Can we get support for the Tape test framework into this release as well? I've just incorporated suggestions after code review into pull request. :)

**Comment by mousetraps** [comment]
@jcansdale -  just took a look at your PR, and left some comments. I think we're cutting it a bit close for Beta, but let's definitely try to include it in the subsequent v1.2 release :smiley:

**Comment by jcansdale** [comment]
How about including just the test adapter and flesh the rest out later? This would be useful to people who already use Tape and virtually invisible to those who don't. Just a suggestion, I'm happy either way. :smile:

**Comment by mousetraps** [comment]
@jcansdale I hear you. However, every code change presents risk, and it's tough to justify taking on risk that's virtually invisible to the user. Technical debt, of course, is a special case, because while there's no immediate return, users "see" increased stability and speed of development.

Anyways, I see that you've updated the PR with item templates, so much thanks! I'll definitely take a look when I get the chance. :smiley: Right now, we're trying to stabilize the release, and it's difficult to justify new features so close to shipping, but we'll at least consider pulling it in because it might be good to get a little more baketime before RTM.

**Comment by jcansdale** [comment]
Thanks for considering it. :)

I was forgetting the 'TestFramework' property isn't a drop down list like for example 'Build Action'. When I said "virtually invisible" earlier, it would have actually have been *completely* invisible (not good).

If 'TestFramework' was also a drop down list, supported frameworks would be discoverable without being intrusive. I don't know how easy this would be, but from what I've seen of the test runner code it would be a good fit. Just a thought...

**Comment by mjbvz** [comment]
<h1 align="center"><a href="https://github.com/Microsoft/nodejstools/releases">🍬 NTVS 1.2 Beta Now Out 🍬</a></h1>

Thank you to everyone who made this release possible!

Please [download and install the beta](https://github.com/Microsoft/nodejstools/releases) and [report any issues you run into](https://github.com/Microsoft/nodejstools/issues/new). You can also share any general feedback on the Beta here: #1077 

----

@jcansdale The beta does include your Tape test framework work. Thanks again for your work here, it really improves the NTVS testing experience and is a great addition.
