### ISSUE TITLE
29 Errors in Starter Node.js Express 3 App

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1037]
It says 45 because I'm still on update 2 and running into #928. 29 of them are unexpected. 
![image](https://cloud.githubusercontent.com/assets/762848/16027600/0c61b424-318c-11e6-9cac-62e09d35f54f.png)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/app.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/_references.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/bootstrap.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/bootstrap.min.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery-1.10.2.intellisense.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery-1.10.2.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery-1.10.2.min.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery.validate-vsdoc.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery.validate.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery.validate.min.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery.validate.unobtrusive.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/jquery.validate.unobtrusive.min.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/modernizr-2.6.2.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/respond.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/public/javascripts/respond.min.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS5055	Cannot write file 'c:/Users/Itani/documents/visual studio 2015/Projects/ExpressApp23/ExpressApp23/routes/index.js' because it would overwrite input file.	ExpressApp23		1	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1005	';' expected.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	2	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1005	';' expected.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	4	Active
Error	TS1127	Invalid character.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\public\javascripts\_references.js	6	Active
Error	TS2307	Cannot find module 'serve-static'.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\typings\globals\express\index.d.ts	4	Active
Error	TS2307	Cannot find module 'express-serve-static-core'.	ExpressApp23	c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\typings\globals\express\index.d.ts	5	Active
```

**Comment by mjbvz** [comment]
Mostly duplicates errors:

* Overwrite errors are from #928 that should be fixed in 2015 U3
* `_references.js` is from #1036 

Not sure about the last two errors:

```
Error   TS2307  Cannot find module 'serve-static'.  ExpressApp23    c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\typings\globals\express\index.d.ts   4   Active
Error   TS2307  Cannot find module 'express-serve-static-core'. ExpressApp23    c:\Users\Itani\documents\visual studio 2015\Projects\ExpressApp23\ExpressApp23\typings\globals\express\index.d.ts   5   Active
````

**Comment by mjbvz** [comment]
We should try getting #1000 in too, which fixes the "Message" about the invalid email address in the `package.json` files. That's not a huge issue, but still a poor first experience. The fix was easy too.

**Comment by mjbvz** [comment]
With the 27 other errors fixed, regarding the `serve-static` and `express-serve-static-core` errors: these packages are referenced in the automatically downloaded `express.d.ts` file but are not installed by typings. This looks to be by design: https://github.com/typings/typings/issues/281

Some options:

* Hard code some logic to automatically acquire these typings wherever we install Express. That only would fix Express obviously, not typings packages that use similar patterns.
* Update our templates to either npm or typings install these two modules. This would only apply to the templates. If a user does a `npm install --save express`, they would then have to manually acquire the typings for these other two packages.

I'm in favor of the second, because it's less clever. Cleverness is usually bad.

**Comment by mjbvz** [comment]
Here's my thinking on how to fully fix this bug, in roughly the order these steps need to be completed:

- [X] #928 The overwrite errors. Should be fixed in VS 2015 Update 3 RTM.
- [X] #1036 The corrupted `_reference.js` files. Fixed now.
- [ ] #1000 This PR fixes the message about the empty `email` in `package.json` files
- [ ] #1051 This PR removes some express 3 templates, reducing the amount of work we need to do for the next steps.
- [ ] #1056 This PR is an experimental fix for the `cannot find module` issues. 
- [ ] Update all JavaScript Express Starter App templates to use Express 4.
- [ ] Apply #1056 or any other fix for the `cannot find module` to all the newly updated JavaScript Express Starter App templates.

I'll create separate issues to track all of this work.
