### ISSUE TITLE
NTVS v1.2 RTM

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1114]
> _**:runner: in progress and preliminary planning notes for next release.**_

This release will ship for:
* VS 2015 (Dev14)

**Emoji legend**
* :hotsprings: [_**red-hots**_](https://github.com/Microsoft/nodejstools/labels/red-hots) (like the candy!): should happen this week, otherwise may impede future efforts
* :busts_in_silhouette: [**_external dependency_**](https://github.com/Microsoft/nodejstools/labels/external): requires coordination
* :no_entry_sign: **_blocked_**
* :crown: **_nice to have_**

##### Issues
This is a minor update to address some of the stability issues present in the current release. Suc hissues include:
* [x] remove global npm node (causing performance issues)
* [x]  typings fails to install when a single .d.ts file is missing

##### Investigations
* [ ] #1105 Very slow and lost custom editor formatting

### User Feedback and engagement
* [x] #965 Agree upon and add any additional telemetry points. So far the interesting ones for this release include:
  * [x] #1096 Add Telemetry for Which IntelliSense Is Currently Selected
* [x] :crown: #1116 Add better diagnostic info for ES6 Mode IntelliSense
* [x] Update VS.COM website
* [x] Blog post

### (Mostly) Code Happiness
* [x] CTI runs
* [ ] Run full test suite
* [ ] Ship party :boat: 

## Targets (subject to change)
* **7/8**: "Big Rocks" complete
* **7/11-7/15:** Stabilization and [release activities](https://github.com/microsoft/nodejstools/wiki/Release-Activities-Checklist)
* **TBD:** Release

**Comment by mjbvz** [comment]
NTVS 1.2 just released: https://github.com/Microsoft/nodejstools/releases
