### ISSUE TITLE
NTVS 1.3 Beta

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#1229]
> _**:runner: in progress and preliminary planning notes for next release.**_

This release will ship for:
* VS 2015 (Dev14)
* VS "15" Preview (Dev15)

For the most part, we will be targeting Dev15 because we want to take advantage of new platform improvements, but we intend to maintain our Dev14 bits in parallel 

**Emoji legend**
* :hotsprings: [_**red-hots**_](https://github.com/Microsoft/nodejstools/labels/red-hots) (like the candy!): should happen this week, otherwise may impede future efforts
* :busts_in_silhouette: [**_external dependency_**](https://github.com/Microsoft/nodejstools/labels/external): requires coordination
* :no_entry_sign: **_blocked_**
* :crown: **_nice to have_**

#### Setup authoring improvements (VS "15")
For this release, we'll continue to test and improve VS "15" setup / acquisition experience 

##### Regressed functionality
* [x] #1222 Azure deployment doesn't work
* [ ] #1180 Cannot Discover Unit Tests
* [ ] #1179 Cannot Find RemoteDebugProxy folder in-progress

#####  Too much functionality
* [ ] #1218 UGH C#/VB get out of my NODE workload! Is that why you're so big??
* [ ] #1223 Default workload install size is 1.2 GB
* [ ] #1220 Profiling component is *huge* (>3GB)
* [ ] #1224 Unnecessary context menu clutter in Node.js workload

##### Node.js Component / Workload definition
 * [x] #1221 Node.js v6 x86 should be recommended in default install

#### Folder-based projects
* [ ] Improve File > Open Folder IntelliSense experience  _**(:busts_in_silhouette: VS Platform - wibu)**_
* [x] Take ownership of debug adapter code
* [ ] Provide "asks" for task runner experience w/ folder-based projects

#### Improved ES6 / IntelliSense experiences
* [x] #1219 F12 on routes.index doesn't work in Dev15 _**(:busts_in_silhouette: TypeScript)**_
* [ ] #1090 Enable ES6 IntelliSense in Node.js Interactive Window _**( :busts_in_silhouette: Roslyn, :busts_in_silhouette: TypeScript)**_
* [ ] #1225 shouldn't generate typings.json in Dev15 project templates

#### Improved Stability and Performance 
* [ ] #443 Interactive Window package should be loaded lazily
* [ ] Investigate and fix miscellaneous stability issues

### User Feedback and engagement
* [x] #965 Agree upon and add any additional telemetry points

### (Mostly) Code Happiness
* [ ] CTI runs
* [ ] driving dev build usage :bulb:

## Targets (subject to change)
* **9/12**: "Big Rocks" complete
* **9/15-9/19:** Stabilization and [release activities](https://github.com/microsoft/nodejstools/wiki/Release-Activities-Checklist)
* **TBD:** Release

**Comment by mjbvz** [comment]
Closing since this is no longer reflects our current plans.

We currently are planning to ship NTVS 1.3 as part of VS 2017. Before VS 2017 is released in its final state, we'll continue to ship preview NTVS 1.3 builds as part of the Node workload. These are essentially our beta/preview releases.

For VS 2015, we're still discussing how we want to release 1.3. The bulk of 1.3 work has been to make NTVS a more stable, performant, and modern Node tool, with a special focus on VS 2017 support. I believe 1.3 has some real benefits, even for VS 2015, but it also brings a few regressions in functionality (such as no IntelliSense in the interactive window and removal of many of our old templates).

Until our plans are better known, I'll keep posting dev builds for VS2015 every week or so. You can also pick up NTVS 1.3 preview builds in VS 2017 ("VS15") by selecting the Node workload in the installer.
