### ISSUE TITLE
NTVS 1.1 patch release

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#691]
Minor update to address some of the stability issues present in the current release. The release should include the following fixes
* [x] #430 Add from existing code should ignore any filepaths that include node_modules and bower_components folders by default
* [x] #604 Runtime syntax error kills Visual Studio
* [x] #692 Investigate and fix stability issues
* [x] #690 Fix async debugger issues
* [x] #697 Fix build machine
* [x] #760 create v1.1 branch, build machines, docs 

This release will ship for:
* VS 2012 (Dev11)
* VS 2013 (Dev12)
* VS 2015 (Dev14)
