### ISSUE TITLE
Investigate and fix miscellaneous stability issues

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#692]
https://github.com/Microsoft/nodejstools/labels/crash-or-hang

**UPDATE** 
As per our investigations, we are hoping to land fixes for the following issues in the next release.
- [x] #684 Inserting a newline in a JS file that has an ill-defined for loop throws an NRE
- [x] #664 Experiencing Intermittent IDE Crashes with NodeJS Tools 1.1

**Comment by mousetraps** [comment]
We are hoping to land fixes for the following issues in the next release.
- [ ] #684 Inserting a newline in a JS file that has an ill-defined for loop throws an NRE
- [ ] #664 Experiencing Intermittent IDE Crashes with NodeJS Tools 1.1
- [ ] #702 Interactive Windows Hangs When Displaying Representation of Object with Many Properties
