### ISSUE TITLE
NTVS vNext Alpha

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#695]
We don't *actually* know what we're going to call this release yet - we'll figure that out later :smiley:.

This release will ship for:
* VS 2015 (Dev14)
* VS vNext (Dev15)

##### Major platform improvements
* [x] #686 Dev15 Support (requires #444)
* [x] #262 Folder-based project support
* [x] #444 Upgrade NTVS to target framework v4.6

##### Improved IntelliSense experiences
* [x] #694 Automatic typings acquisition
* [x] #687 Enable Salsa by default

##### More reliable debugging
* [x] #690 Fix async debugger issues

##### Stability and performance
* [x] #604 Runtime syntax error kills Visual Studio
* [x] #430 Add from existing code should ignore any filepaths that include node_modules and bower_components folders by default
* [x] #692 Investigate and fix miscellaneous stability issues

##### Node.js v6 support
* [x] #745 Node.js v6 support

### Code Happiness
* [x] #697 Fix build machine
* [x] #751 Set up Dev15 build machine
* [x] #689 AppVeyor CI -> 100% passing

## Targets (subject to change)
* **3/19**: "Big Rocks" complete
* **3/19-3/26:** Stabilization and [release activities](https://github.com/microsoft/nodejstools/wiki/Release-Activities-Checklist)
* **TBD:** Release

**Comment by mousetraps** [comment]
new release available at https://github.com/Microsoft/nodejstools/releases
