### ISSUE TITLE
NTVS v1.3 Alpha

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#948]
> _**:runner: in progress and preliminary planning notes for next release.**_

This release will ship for:
* VS 2015 (Dev14)
* VS "15" Preview (Dev15)

**Emoji legend**
* :hotsprings: [_**red-hots**_](https://github.com/Microsoft/nodejstools/labels/red-hots) (like the candy!): should happen this week, otherwise may impede future efforts
* :busts_in_silhouette: [**_external dependency_**](https://github.com/Microsoft/nodejstools/labels/external): requires coordination
* :no_entry_sign: **_blocked_**
* :crown: **_nice to have_**

##### Major platform improvements (VS "15")

* [x] #821 Lightweight Visual Studio Installer _**(:busts_in_silhouette: VS Platform - pm: tims, dev: huyn)**_
  * [x] :hotsprings: #954 Create modern NTVS extension
  * [x] :hotsprings: #955 Update build / signing scripts to build for lightweight installer
  * [x] :hotsprings: #956 Appear in VS "15" Preview Installer Feed
  * [x] :hotsprings: #957 Verify chaining in partner dependencies (Salsa, Web Tools) with Lightweight VS installer
* [ ] :crown: Improve File > Open Folder IntelliSense experience  _**(:busts_in_silhouette: VS Platform - wibu)**_
  * [ ] Take ownership of debug adapter code
  * [ ] #1112 Investigate open Qs

##### Improved ES6 / IntelliSense experiences
* [ ] #1090 Enable ES6 IntelliSense in Node.js Interactive Window

##### Improved build and deployment experiences
* [ ] :crown: Investigate hooking up task runner with existing project system

##### Improved Stability and Performance 
* [ ] Investigate and fix miscellaneous stability issues

### User Feedback and engagement
* [x] #965 Agree upon and add any additional telemetry points

### (Mostly) Code Happiness
* [x] CTI runs
* [ ] driving dev build usage :bulb:

## Targets (subject to change)
* **7/22**: "Big Rocks" complete
* **7/25-7/29:** Stabilization and [release activities](https://github.com/microsoft/nodejstools/wiki/Release-Activities-Checklist)
* **TBD:** Release

**Comment by mousetraps** [comment]
Closing this, as "Alpha" has been released with [Visual Studio "15" Preview 4](https://blogs.msdn.microsoft.com/visualstudio/2016/08/22/visual-studio-15-preview-4/) as part of the Node.js workload. The lightweight install work was relatively involved and we had some other competing priorities, so we didn't quite finish up with everything, but more to come in our 1.3 Beta plan
