### ISSUE TITLE
Investigate and fix miscellaneous stability issues for v1.2 Beta

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#962]
* [x] #881 Stop leaking NodejsFolderNodes
  * [x] #967 Fix potential leak/null reference when switching projects
  * [x] #926 Adding a few more nullchecks to AnalyzeWorker 
  * [x] #987 Reorder TryDeactivateSymLinkWatcher in call to prevent leak/crash
