### ISSUE TITLE
Agree upon and add any additional telemetry points

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejstools#965]
> :runner: in progress and preliminary

In particular, the following would give us valuable metrics to help improve the product:
* [x] #332 Add telemetry to allow us to detect ppl/scenarios affected by inconsistent debug experiences
* [x] #1096 Add Telemetry for Which IntelliSense Is Currently Selected
* [ ] #1115 Add telemetry to detect project characteristics that help drive performance improvements
* To be decided!

**Comment by mjbvz** [comment]
Closing since we've addressed the original goals here and investigated telemetry for NTVS 1.2. We still always should be thinking about any telemetry points that would be helpful, but will track those with new issues as they come in.
